### ISSUE TITLE
Directory mode potential performance improvement

### ISSUE THREAD

**Issue by BoySanic** [DeadSix27/waifu2x-converter-cpp#248] opened 2020-06-07 14:40 UTC
Something I've noticed while using this program is that it really only does one file at a time. As though the directory mode is simply a for loop over files in the directory, running exactly as a single file would but for all files in that directory.

What I propose is that while the OpenCL device (or CUDA device) is doing some work, we load more images into memory ready to be converted with the w2xconv_convert_mat function, that way we reduce the downtime of the target device.

This can be done one of a few ways, in my mind.

1. Load all images in a directory into memory, then use the w2xconv_convert_mat function on all loaded images in a loop, then output them all to file at the very end.
2. Load some images from the source directory into memory, perform work on those, and as work is being performed, load more images into memory.

Either of these options can help reduce the downtime of the OpenCL (or CUDA) device and I believe it will show a significant uplift in performance for many devices. 
![mstsc_wo2Iq1mHrt](https://user-images.githubusercontent.com/26152620/83971773-14334600-a8ab-11ea-9e9d-4da9053969c7.png)

Shown above is how much downtime the target device sees while working through a huge directory of images.

Let me know if you have any questions! I was beginning to "hack" something together for this, but I barely have any understanding of how the core of this program really works, so I feel such a huge optimization might be better done by those who maintain it.

Thanks!

**Comment by kattjevfel** [comment] 2020-06-07 20:34
This sounds like a duplicate of #36

**Comment by YukihoAA** [comment] 2020-12-13 09:57
In case if we pre-load image to memory will take huge memory of system, it will make many page faults which makes conversion slower. so implement multi-threaded imwrite is best option for now. so your suggestion will be handled with #36 thank you.

**Closed by YukihoAA** 2020-12-13 09:57 UTC
